DROP TABLE TASK IF EXISTS;

CREATE TABLE TASK
(
    `ID`          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '할 일 ID',
    `STATUS`      VARCHAR(64)  NOT NULL COMMENT '진행상태',
    `TITLE`       VARCHAR(128) NOT NULL COMMENT '할 일 제목',
    `DESCRIPTION` VARCHAR(512) NOT NULL COMMENT '할 일 설명',
    `DUE_DATE`    DATE NULL     COMMENT '목표 완료 시간',
    `CREATED_AT`  TIMESTAMP(6) NOT NULL COMMENT '생성 날짜',
    `UPDATED_AT`  TIMESTAMP(6) NOT NULL COMMENT '수정 날짜'
);